# Generated by Django 2.0.7 on 2018-07-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_category',
            field=models.CharField(choices=[('cosmetology', 'Косметология'), ('surgery', 'Хирургия')], default=1, max_length=20, verbose_name='Категория услуги'),
            preserve_default=False,
        ),
    ]
