# Generated by Django 2.0.7 on 2018-07-15 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_service_service_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Наименование')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Образование и курсы специалистов',
                'verbose_name': 'объект',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Специализации')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Список специализаций',
                'verbose_name': 'объект',
            },
        ),
        migrations.AddField(
            model_name='specialist',
            name='experience',
            field=models.PositiveIntegerField(default=1, verbose_name='Стаж работы (лет)'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialist',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='specialist',
            name='courses',
            field=models.ManyToManyField(null=True, related_name='courses', to='main.Course', verbose_name='Образование и курсы'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='specialization',
            field=models.ManyToManyField(null=True, related_name='specialization', to='main.Specialization', verbose_name='Список специализаций'),
        ),
    ]
