# Generated by Django 2.0.7 on 2018-07-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('face', 'Лицо/Голова'), ('hand', 'Руки, ноги'), ('chest', 'Грудь'), ('hip', 'Живот, бока и ягодицы'), ('pussy', 'Интимная зона'), ('legs', 'Ноги')], max_length=20, verbose_name='Тип услуги'),
        ),
    ]
