# Generated by Django 2.0.7 on 2018-08-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180808_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='courses',
            field=models.ManyToManyField(related_name='courses', to='main.Course', verbose_name='Образование и курсы'),
        ),
    ]
