# Generated by Django 2.0.7 on 2018-08-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180808_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='experience',
            field=models.CharField(default='', max_length=255, verbose_name='Стаж работы (лет)'),
        ),
    ]
