# Generated by Django 2.0.7 on 2018-08-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20180808_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='number',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Порядковый номер'),
            preserve_default=False,
        ),
    ]
