# Generated by Django 2.0.7 on 2018-09-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_work_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutimage',
            name='number',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Порядковый номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='number',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Порядковый номер'),
            preserve_default=False,
        ),
    ]
